export const listTableSchema = [
  {
    company: "GO AIR",
    issueDate: "4th - 7th Oct 2022",
    issueSize: "₹3600 Crores",
    priceRange: "₹50-60",
    minInvestment: "₹50,000",
    minInvestmentDate: "100 Shares/5 Lots",
    logo: "/images/go air.jpg",
    link: "/detailpage",
  },
  {
    company: "BAJAJ ENERGY",
    issueDate: "4th - 7th Oct 2022",
    issueSize: "₹3600 Crores",
    priceRange: "₹50-60",
    minInvestment: "₹50,000",
    minInvestmentDate: "100 Shares/5 Lots",
    logo: "/images/Bajaj_Energy_logo.jpg",
    link: "/detailpage",
  },
  {
    company: "OYO",
    issueDate: "To be announced",
    issueSize: "₹3600 Crores",
    priceRange: "₹50-60",
    minInvestment: "₹50,000",
    minInvestmentDate: "100 Shares/5 Lots",
    logo: "/images/oyo.png",
    link: "/detailpage",
  },
  {
    company: "TATA ENERGY",
    issueDate: "4th - 7th Oct 2022",
    issueSize: "₹3600 Crores",
    priceRange: "₹50-60",
    minInvestment: "₹50,000",
    minInvestmentDate: "100 Shares/5 Lots",
    logo: "/images/tata-power.jpg",
    link: "/detailpage",
  },
];
